name: closr_screens
description: A new Flutter project.

version: 1.0.0+1

environment:
  # sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^0.9.3
  flutter_bloc: ^0.7.0
  meta: ^1.1.6
  equatable: ^0.2.0
  quick_actions: ^0.3.0+1
  unicorndial: ^1.1.5
  flutter_staggered_grid_view: ^0.3.0
  flutter_sparkline: ^0.1.0


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
